const mongoose = require('mongoose');

// Imporatmos el modelo Character en este nuevo archivo.
const Character = require('../characters/character.model');
mongoose.set('strictQuery', false)
const characters = [
    {
        
        "name": "Daenerys Targaryen",
        "gender": "female",
        "born": "282 AC",
        "origin": "Dragonstone",
        "death": "",
        "status": "alive",
        "culture": "Valyrian",
        "religion": "",
        "titles": [
          "Queen of the Andals, the Rhoynar, and the First Men",
          "Protector of the Seven Kingdoms",
          "Khaleesi of the Great Grass Sea",
          "Lady of Dragonstone",
          "Breaker of Chains",
          "Mother of Dragons",
          "Queen of Meereen"
        ],
        "house": "Targaryen",
      },
      {
        
        "name": "Viserys Targaryen",
        "gender": "male",
        "born": "276 AC",
        "origin": "King's Landing",
        "death": "298 AC",
        "status": "deceased",
        "culture": "Valyrian",
        "religion": "The Sevens",
        "titles": ["Kings of the Andals and the First Men", "Lord of the Seven Kingdoms", "Protector of the Realm", "Prince"],
        "house": "Targaryen",
      },
      {
        
        "name": "Jon Snow",
        "gender": "male",
        "born": "281 AC",
        "origin": "Tower of Joy",
        "death": "302 AC",
        "status": "resurrected",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Warden of the North", "King in the North", "Lord Commander of the Night's Watch"],
        "house": "Targaryen",
      },
      {
      
        "name": "Robb Stark",
        "gender": "male",
        "born": "281 AC",
        "origin": "Riverrun",
        "death": "300 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["King of the North", "Lord of Winterfell", "Lord Paramount of the North"],
        "house": "Stark",
      },
      {
        
        "name": "Sansa Stark",
        "gender": "female",
        "born": "285 AC",
        "origin": "Winterfell",
        "death": "",
        "status": "alive",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lady of Winterfell", "Princess of the North", "Lady Regent of the North"],
        "house": "Stark",
      },
      {
        
        "name": "Arya Stark",
        "gender": "female",
        "born": "287 AC",
        "origin": "Winterfell",
        "death": "",
        "status": "alive",
        "culture": "Northmen",
        "religion": "Many-Faced God",
        "titles": ["Princess of the North"],
        "house": "Stark",
      },
      {
        
        "name": "Brandon Stark",
        "gender": "male",
        "born": "288 AC",
        "origin": "Winterfell",
        "death": "",
        "status": "alive",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of Winterfell", "Prince of the North"],
        "house": "Stark",
      },
      {
       
        "name": "Rickon Stark",
        "gender": "male",
        "born": "292 AC",
        "origin": "Winterfell",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Prince of the North"],
        "house": "Stark",
      },
      {
        
        "name": "Benjen Stark",
        "gender": "male",
        "born": "",
        "origin": "Winterfell",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["First Ranger"],
        "house": "Stark",
      },
      {
        
        "name": "Eddard Stark",
        "gender": "male",
        "born": "",
        "origin": "Winterfell",
        "death": "298 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of Winterfell", "Lord Paramount of the North", "Warden of the North", "Hand of the King", "Lord Regent of the Seven Kingdoms", "Protector of the Realm"],
        "house": "Stark",
      },
      {
       
        "name": "Catelyn Tully",
        "gender": "female",
        "born": "",
        "origin": "Riverrun",
        "death": "300 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Queen Mother"],
        "house": "Tully",
      },
      {
        
        "name": "Edmure Tully",
        "gender": "male",
        "born": "",
        "origin": "Riverrun",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Ser", "Lord of Riverrun", "Lord Paramount of the Trident"],
        "house": "Tully",
      },
      {
       
        "name": "Hoster Tully",
        "gender": "male",
        "born": "",
        "origin": "Riverrun",
        "death": "300 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Riverrun", "Lord Paramount of the Trident"],
        "house": "Tully",
      },
      {
       
        "name": "Brynden Tully",
        "gender": "male",
        "born": "240 AC",
        "origin": "Riverrun",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Ser", "Lord of Riverrun"],
        "house": "Tully",
      },
      {
       
        "name": "Lisa Tully",
        "gender": "female",
        "born": "",
        "origin": "Riverrun",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lady Regent of the Vale"],
        "house": "Tully",
      },
      {
       
        "name": "Jon Arryn",
        "gender": "male",
        "born": "298 AC",
        "origin": "The Eyrie",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Hand of the King", "Lord of the Eyrie", "Defender of the Vale", "Warden of the East"],
        "house": "Arryn",
      },
      {
       
        "name": "Robin Arryn",
        "gender": "male",
        "born": "289 AC",
        "origin": "King's Landing",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of the Eyrie", "Defender of the Vale", "Warden of the East"],
        "house": "Arryn",
      },
      {
        
        "name": "Yohn Royce",
        "gender": "male",
        "born": "",
        "origin": "Runestone",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Runestone"],
        "house": "Royce",
      },
      {
        
        "name": "Tywin Lannister",
        "gender": "male",
        "born": "234 AC",
        "origin": "Casterly Rock",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Casterly Rock", "Lord Paramount of the Westerlands", "Warden of the West", "Shield of Lannisport", "Hand of the King", "Protector of the Realm", "Savior of the City"],
        "house": "Lannister",
      },
      {
        
        "name": "Kevan Lannister",
        "gender": "male",
        "born": "",
        "origin": "Casterly Rock",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Ser", "Hand of the King", "Protector of the Realm"],
        "house": "Lannister",
      },
      {
       
        "name": "Lancel Lannister",
        "gender": "male",
        "born": "",
        "origin": "Casterly Rock",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Ser"],
        "house": "Lannister",
      },
      {
        
        "name": "Tyrion Lannister",
        "gender": "male",
        "born": "266 AC",
        "origin": "Casterly Rock",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Casterly Rock", "Lord Paramount of the Westerlands", "Warden of the West", "Hand of the Queen", "Master of Coin", "Hand of the King"],
        "house": "Lannister",
      },
      {
        
        "name": "Jaime Lannister",
        "gender": "male",
        "born": "262 AC",
        "origin": "Casterly Rock",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord Commander of the Kingsguard"],
        "house": "Lannister",
      },
      {
       
        "name": "Cersei Lannister",
        "gender": "female",
        "born": "262 AC",
        "origin": "Casterly Rock",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": [
          "Queen of the Andals and the First Men",
          "Protector of the Seven Kingdoms",
          "Lady of Casterly Rock",
          "Lady Paramount of the Westerlands",
          "Wardeness of the West",
          "Queen Mother",
          "Queen Regent",
          "Queen Consort"
        ],
        "house": "Lannister",
      },
      {
       
        "name": "Joffrey Lannister",
        "gender": "male",
        "born": "282 AC",
        "origin": "King's Landing",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["King of the Andals and the First Men", "Lord of the Seven Kingdoms", "Protector of the Realm", "Lord of Storm's End", "Lord Paramount of the Stormlands"],
        "house": "Lannister",
      },
      {
        
        "name": "Myrcella Lannister",
        "gender": "female",
        "born": "283 AC",
        "origin": "King's Landing",
        "death": "302 AC",
        "status": "deaceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Princess"],
        "house": "Lannister",
      },
    {
        
        "name": "Tommen Lannister",
        "gender": "male",
        "born": "287 AC",
        "origin": "King's Landing",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["King of the Andals and the First Men", "Lord of the Seven Kingdoms", "Protector of the Realm", "Lord of Storm's End", "Lord Paramount of the Stormlands"],
        "house": "Lannister",
    },
    {
       
        "name": "Robert Baratheon",
        "gender": "male",
        "born": "",
        "origin": "Storm's End",
        "death": "298 AC",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["King of the Andals and the First Men", "Lord of the Seven Kingdoms", "Protector of the Realm", "Lord of Storm's End", "Lord Paramount of the Stormlands"],
        "house": "Baratheon",
      },
      {
        
        "name": "Renly Baratheon",
        "gender": "male",
        "born": "",
        "origin": "Storm's End",
        "death": "299 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["King of the Andals and the First Men", "Lord of the Seven Kingdoms", "Protector of the Realm", "Lord of Storm's End", "Lord Paramount of the Stormlands", "Master of Laws"],
        "house": "Baratheon",
      },
      {
       
        "name": "Stannis Baratheon",
        "gender": "male",
        "born": "",
        "origin": "Storm's End",
        "death": "302 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "R'hllor",
        "titles": [
          "King of the Andals and the First Men",
          "Lord of the Seven Kingdoms",
          "Protector of the Realm",
          "Lord of Storm's End",
          "Lord Paramount of the Stormlands",
          "Lord of Dragonstone",
          "Master of Ships"
        ],
        "house": "Baratheon",
      },
      {
      
        "name": "Selyse Florent",
        "gender": "female",
        "born": "",
        "origin": "Brighwater Keep",
        "death": "302 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "R'hllor",
        "titles": ["Queen Consort"],
        "house": "Florent",
      },
      {
        
        "name": "Shireen Baratheon",
        "gender": "female",
        "born": "287 AC",
        "origin": "Dragonstone",
        "death": "302 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "",
        "titles": ["Princess"],
        "house": "Baratheon",
      },
      {
        
        "name": "Olenna Tyrell",
        "gender": "female",
        "born": "",
        "origin": "The Arbor",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": [],
        "house": "Tyrell",
      },
      {
       
        "name": "Mace Tyrell",
        "gender": "male",
        "born": "",
        "origin": "Highgarden",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Highgarden", "Lord Paramount of the Reach", "Warden of the South", "Master of Ships", "Master of Coin", "Hand of the King"],
        "house": "Tyrell",
      },
      {
       
        "name": "Loras Tyrell",
        "gender": "male",
        "born": "",
        "origin": "Highgarden",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Ser", "Lord Commander of the Kingsguard"],
        "house": "Tyrell",
      },
      {
       
        "name": "Margaery Tyrell",
        "gender": "female",
        "born": "",
        "origin": "Highgarden",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Queen Consort"],
        "house": "Tyrell",
      },
      {
        
        "name": "Balon Greyjoy",
        "gender": "male",
        "born": "",
        "origin": "Pyke",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Ironborn",
        "religion": "Drowned God",
        "titles": ["King of the Iron Islands", "King of Salt and Rock", "Son of the Sea Wind", "Lord Reaper of Pyke", "Lord of the Iron Islands"],
        "house": "Greyjoy",
      },
      {
       
        "name": "Euron Greyjoy",
        "gender": "male",
        "born": "",
        "origin": "Pyke",
        "death": "",
        "status": "alive",
        "culture": "Ironborn",
        "religion": "Drowned God",
        "titles": ["King of the Iron Islands", "King of Salt and Rock", "Son of the Sea Wind", "Lord Reaper of Pyke"],
        "house": "Greyjoy",
      },
      {
        
        "name": "Theon Greyjoy",
        "gender": "male",
        "born": "281 AC",
        "origin": "Pyke",
        "death": "",
        "status": "alive",
        "culture": "Ironborn",
        "religion": "Drowned God",
        "titles": [],
        "house": "Greyjoy",
      },
      {
        
        "name": "Yara Greyjoy",
        "gender": "female",
        "born": "281 AC",
        "origin": "Pyke",
        "death": "",
        "status": "alive",
        "culture": "Ironborn",
        "religion": "Drowned God",
        "titles": ["Queen of the Iron Islands", "Queen of Salt and Rock", "Daughter of the Sea Wind", "Lady Reaper of Pyke"],
        "house": "Greyjoy",
      },
      {
       
        "name": "Doran Martell",
        "gender": "male",
        "born": "",
        "origin": "Sunspear",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": ["Prince of Dorne", "Lord of Sunspear"],
        "house": "Martell",
      },
      {
        
        "name": "Oberyn Martell",
        "gender": "male",
        "born": "",
        "origin": "Sunspear",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": ["Prince"],
        "house": "Martell",
      },
      {
       
        "name": "Trystane Martell",
        "gender": "male",
        "born": "",
        "origin": "Sunspear",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": ["Prince"],
        "house": "Martell",
      },
      {
       
        "name": "Ellaria Sand",
        "gender": "female",
        "born": "",
        "origin": "Hellholt",
        "death": "",
        "status": "alive",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": ["Prince"],
        "house": "Uller",
      },
      {
       
        "name": "Obara Sand",
        "gender": "female",
        "born": "",
        "origin": "Dorne",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": [],
        "house": "Martell",
      },
      {
        
        "name": "Nymeria Sand",
        "gender": "female",
        "born": "",
        "origin": "Dorne",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": [],
        "house": "Martell",
      },
      {
       
        "name": "Tyene Sand",
        "gender": "female",
        "born": "",
        "origin": "Dorne",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Dornish",
        "religion": "The Sevens",
        "titles": [],
        "house": "Martell",
      },
      {
        
        "name": "Randyll Tarly",
        "gender": "male",
        "born": "",
        "origin": "Horn Hill",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Lord of Horn Hill"],
        "house": "Tarly",
      },
      {
       
        "name": "Dickon Tarly",
        "gender": "male",
        "born": "",
        "origin": "Horn Hill",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": [],
        "house": "Tarly",
      },
      {
       
        "name": "Samwell Tarly",
        "gender": "male",
        "born": "280 AC",
        "origin": "Horn Hill",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "Old Gods",
        "titles": [],
        "house": "Tarly",
      },
      {
     
        "name": "Jeor Mormont",
        "gender": "male",
        "born": "280 AC",
        "origin": "Bear Island",
        "death": "300 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of Bear Island", "Lord Commander of the Night's Watch"],
        "house": "Mormont",
      },
      {
        
        "name": "Jorah Mormont",
        "gender": "male",
        "born": "280 AC",
        "origin": "Bear Island",
        "death": "",
        "status": "alive",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of Bear Island", "Ser"],
        "house": "Mormont",
      },
      {
       
        "name": "Petyr Baelish",
        "gender": "male",
        "born": "",
        "origin": "Baelish Castle",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "Drowned God",
        "titles": ["Lord Protector of the Vale", "Lord of Harrenhal", "Master of Coin"],
        "house": "Baelish",
      },
      {
        
        "name": "Davos Seaworth",
        "gender": "male",
        "born": "",
        "origin": "King's Landing",
        "death": "304 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "",
        "titles": ["Hand of the King", "Ser"],
        "house": "Seaworth",
      },
      {
       
        "name": "Brienne of Tarth",
        "gender": "female",
        "born": "",
        "origin": "Evenfall Hall",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["Kingsguard"],
        "house": "Tarth",
      },
      {
        
        "name": "Sandor Clegane",
        "gender": "male",
        "born": "",
        "origin": "Clegane's Keep",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "",
        "titles": ["Kingsguard"],
        "house": "Clegane",
      },
      {
        
        "name": "Varys",
        "gender": "male",
        "born": "",
        "origin": "Lys",
        "death": "",
        "status": "alive",
        "culture": "Lysene",
        "religion": "",
        "titles": ["Master of Whisperers"],
        "house": "Unknown",
      },
      {
       
        "name": "Bronn",
        "gender": "male",
        "born": "",
        "origin": "",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "",
        "titles": ["Ser", "Commander of the City Watch"],
        "house": "Unknown",
      },
      {
       
        "name": "Melisandre",
        "gender": "female",
        "born": "97 AC",
        "origin": "Asshai",
        "death": "",
        "status": "alive",
        "culture": "Asshai'i",
        "religion": "R'hllor",
        "titles": [],
        "house": "Unknown",
      },
      {
       
        "name": "Ramsay Bolton",
        "gender": "male",
        "born": "",
        "origin": "The DreadFort",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of the Dreadfort", "Lord of Winterfell", "Lord Paramount of the North", "Warden of the North"],
        "house": "Bolton",
      },
      {
       
        "name": "Roose Bolton",
        "gender": "male",
        "born": "",
        "origin": "The DreadFort",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lord of the Dreadfort", "Lord of Winterfell", "Lord Paramount of the North", "Warden of the North"],
        "house": "Bolton",
      },
      {
        
        "name": "Missandei",
        "gender": "female",
        "born": "",
        "origin": "Naath",
        "death": "",
        "status": "alive",
        "culture": "Naathi",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
        
        "name": "Grey Worm",
        "gender": "female",
        "born": "",
        "origin": "Summer Isles",
        "death": "",
        "status": "alive",
        "culture": "Summer Islander",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
        
        "name": "Gilly",
        "gender": "female",
        "born": "",
        "origin": "Craster's Keep",
        "death": "",
        "status": "alive",
        "culture": "Free Folk",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
       
        "name": "Ygritte",
        "gender": "female",
        "born": "",
        "origin": "Beyond the Wall",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Free Folk",
        "religion": "",
        "titles": [],
        "house": "Unknown",
        
      },
      {
      
        "name": "Tormund",
        "gender": "male",
        "born": "",
        "origin": "Beyond the Wall",
        "death": "",
        "status": "alive",
        "culture": "Free Folk",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
        
        "name": "Shae",
        "gender": "female",
        "born": "276 AC",
        "origin": "Lorath",
        "death": "301 AC",
        "status": "deceased",
        "culture": "Lorathi",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
       
        "name": "Jaqen H'ghar",
        "gender": "male",
        "born": "",
        "origin": "Braavos",
        "death": "",
        "status": "alive",
        "culture": "Braavosi",
        "religion": "Many-Faced God",
        "titles": [],
        "house": "Unknown",
      },
      {
      
        "name": "Drogo",
        "gender": "male",
        "born": "",
        "origin": "Vaes Dothrak",
        "death": "298 AC",
        "status": "deceased",
        "culture": "Dothraki",
        "religion": "Great Stallion",
        "titles": ["Khal"],
        "house": "Unknown",
      },
      {
       
        "name": "Daario Naharis",
        "gender": "male",
        "born": "",
        "origin": "Tyrosh",
        "death": "",
        "status": "alive",
        "culture": "Tyroshi",
        "religion": "",
        "titles": ["Regent of the Bay of Dragons"],
        "house": "Unknown",
      },
      {
       
        "name": "Gendry",
        "gender": "male",
        "born": "",
        "origin": "King's Landing",
        "death": "",
        "status": "alive",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": [],
        "house": "Unknown",
      },
      {
     
        "name": "High Sparrow",
        "gender": "male",
        "born": "",
        "origin": "King's Landing",
        "death": "303 AC",
        "status": "deceased",
        "culture": "Andal",
        "religion": "The Sevens",
        "titles": ["High Septon"],
        "house": "Unknown",
      },
      {
      
        "name": "Talisa Maegyr",
        "gender": "female",
        "born": "",
        "origin": "Volantis",
        "death": "300 AC",
        "status": "deceased",
        "culture": "Volantene",
        "religion": "The Sevens",
        "titles": ["Queen Consort"],
        "house": "Unknown",
      },
      {
     
        "name": "The Night King",
        "gender": "male",
        "born": "~12 000 BC",
        "origin": "Beyond the Wall",
        "death": "",
        "status": "alive",
        "culture": "White Walkers",
        "religion": "",
        "titles": [],
        "house": "Unknown",
      },
      {
      
        "name": "Rhaegar Targaryen",
        "gender": "male",
        "born": "",
        "origin": "King's Landing",
        "death": "281 AC",
        "status": "Deceased",
        "culture": "Valyrian",
        "religion": "The Sevens",
        "titles": ["Prince of Dragonstone"],
        "house": "Targaryen",
      },
      {
       
        "name": "Lyanna Mormont",
        "gender": "female",
        "born": "292 AC",
        "origin": "Bear Island",
        "death": "",
        "status": "alive",
        "culture": "Northmen",
        "religion": "Old Gods",
        "titles": ["Lady of Bear Island"],
        "house": "Mormont",
      }
]

mongoose
  .connect("mongodb+srv://root:root@cluster0.medc7xx.mongodb.net/got-2?retryWrites=true&w=majority", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(async () => {
		// Utilizando Color.find() obtendremos un array con todos los colores de la db
    const allCharacters = await Character.find();
		
		// Si existen colores previamente, dropearemos la colección
    if (allCharacters.length) {
      await Character.collection.drop(); //La función drop borra la colección
      console.log('Drop database')
    }
  })
  .catch((err) => console.log(`Error deleting data: ${err}`))
  .then(async () => {
		// Una vez vaciada la db de los colores, usaremos el array colors
		// para llenar nuestra base de datos con todas los colores.
		await Character.insertMany(characters);
        console.log('DatabaseCreated')
	})
  .catch((err) => console.log(`Error creating data: ${err}`))
	// Por último nos desconectaremos de la DB.
  .finally(() => mongoose.disconnect());